### ISSUE TITLE
How about adding optional parameters?

### ISSUE THREAD

**Issue by MariaAguiar** [dadoming/SortPeopleIntoTeams#1]
I loved the idea!
I wonder if you could add sorting options and criteria, like seniority or role.
Giving more optional columns to the base csv and sort by same or different values in those columns, by adding the column names as parameters to the program, for example :)
If you give more then one column name, the first given column is mandatory, and the next ones nice-to-have?
Just an idea!
Thanks!

**Comment by dadoming** [comment]
If you wanna do it then go for it and make a pull request !! Any improvement in the algorithm is appreciated !

**Comment by MariaAguiar** [comment]
Challenge accepted and trial version done!
Thank you! 😉
